### ISSUE TITLE
How to configure validation using this schema in 3.4.X without metadata/editor/schemaConfig?

### ISSUE THREAD

**Issue by metazool** [metadata101/iso19139.gemini22#2]
Hello,

I'm trying to set up this plugin for GeoNetwork 3.4.x but can't follow the README all the way through as the `schemaConfig` setting referred to in the README appears to have been removed in the latest GeoNetwork version.

From the README: "Adding editor configuration
Once the application started, check the plugin is loaded in the admin > standard page. Then in admin > Settings, add to metadata/editor/schemaConfig the editor configuration for the schema:"

The 3.4.x migration script shows this setting being deleted, https://github.com/geonetwork/core-geonetwork/blob/49074582ebfa07f42139f5f9f6de03aeda3a344d/web/src/main/webapp/WEB-INF/classes/setup/sql/migrate/v340/migrate-default.sql

There's a `removeSchemaLocation` option to stop autodetecting XSD to validate against but I can't see how to specify schema validation against GEMINI 2.2 or another custom schema...

**Comment by archaeogeek** [comment]
Hi Jo, for now, clone the version at https://github.com/AstunTechnology/iso19139.gemini22_GN3 as the conversion to 3.4.x is an active work in progress and this fork is not quite up to date. The schemaconfig is now in layout/config-editor.xml, I just haven't updated the readme yet, sorry!

**Comment by metazool** [comment]
Excellent thanks i'll clone the upstream version ... cheers Jo :D

**Comment by archaeogeek** [comment]
@metazool 

I've brought this version up to date with the upstream version, and modified the readmes for both the 3.2.x branch (to say it should only be used with Geonetwork 3.2.x) and the 3.4.x branch (to say it should only be used with Geonetwork 3.4.x and to include the section on the config-editor configuration for the side panels). Hope that clears things up! OK to close this?

Jo
