### ISSUE TITLE
getcapabilities spelling is incorrect

### ISSUE THREAD

**Issue by nmtoken** [metadata101/iso19139.gemini22#9]
In commit 

https://github.com/metadata101/iso19139.gemini22/pull/7/commits/ca37d2502010a8d8cbf66d1ada1581534ef652eb

request=getcapabailities is incorrect. OGC standard (OWS common) tells us it must be case sensitive request=GetCapabilities

@nmtoken thanks for the catch- indeed it's in src/main/plugin/iso19139.gemini22/convert/OGCWxSGetCapabilitiesto19119/OGCWxSGetCapabilitiesLayer-to-19139.xsl. Please create an issue for this (and anything else you find)

_Originally posted by @archaeogeek in https://github.com/metadata101/iso19139.gemini22/pull/7#issuecomment-535932827_

**Comment by archaeogeek** [comment]
@ianturton could you check and test this- it may occur elsewhere in those xsl too- and should be applied in the main Astun repository, thanks
